spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_point_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# JWT Configuration
app:
  jwtSecret: your-secret-key-here-make-it-long-and-secure-in-production
  jwtExpirationInMs: 86400000

# Logging configuration
logging:
  level:
    gympoint.backend.subscriptionservice: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

# Swagger configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true 